import { useEffect, useState } from 'react';
import { BookOpenCheck, Eye, EyeOff, Plus, RefreshCw, Save, Settings, ShieldCheck } from 'lucide-react';
import { APP_FEATURES, type AdminUserData, type AppFeatureKey, type AuditLogData, type ConfigurableRuleData, type FeatureVisibilityData } from '@socialapp/shared';
import { api } from '../lib/api';
import { createId } from '../lib/uuid';

type Overview={users:AdminUserData[];rules:ConfigurableRuleData[];auditLogs:AuditLogData[];catalogs:Record<string,{id:string;name:string;active:boolean}[]>;instruments:{id:string;name:string;version:number;questions:unknown[]}[]};
export function AdminPage(){
 const [data,setData]=useState<Overview>();const[tab,setTab]=useState<'users'|'sections'|'catalogs'|'rules'|'instruments'|'audit'>('users');const[message,setMessage]=useState('');
 async function load(){try{setData(await api.adminOverview() as unknown as Overview)}catch(error){setMessage(error instanceof Error?error.message:'No fue posible abrir administración.')}}
 useEffect(()=>{void load()},[]);
 if(!data)return <div className="card p-10 text-center"><Settings className="mx-auto text-slate-300"/><p className="mt-3 text-sm text-slate-500">{message||'Cargando administración…'}</p></div>;
 return <div><div><p className="text-sm font-bold text-coral-600">Configuración institucional</p><h1 className="font-display text-4xl text-pine-900">Administración</h1><p className="mt-2 text-sm text-slate-500">Usuarios, visibilidad de secciones, catálogos, instrumentos, reglas configurables y auditoría.</p></div>{message&&<p className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">{message}</p>}<div className="mt-6 flex gap-2 overflow-x-auto">{([['users','Usuarios'],['sections','Secciones'],['catalogs','Catálogos'],['rules','Reglas'],['instruments','Instrumentos'],['audit','Auditoría']] as const).map(([v,l])=><button key={v} onClick={()=>setTab(v)} className={`min-h-11 shrink-0 rounded-xl px-4 text-sm font-semibold ${tab===v?'bg-pine-800 text-white':'bg-white text-pine-800'}`}>{l}</button>)}</div>
 {tab==='users'&&<Users data={data.users} reload={load} notify={setMessage}/>}
 {tab==='sections'&&<FeatureSections notify={setMessage}/>}
 {tab==='catalogs'&&<Catalogs data={data.catalogs} reload={load} notify={setMessage}/>}
 {tab==='rules'&&<Rules data={data.rules} reload={load} notify={setMessage}/>}
 {tab==='instruments'&&<Instruments data={data.instruments} reload={load} notify={setMessage}/>}
 {tab==='audit'&&<Audit data={data.auditLogs}/>}</div>
}

const featureLabels: Record<AppFeatureKey, { name: string; description: string }> = {
 [APP_FEATURES.ATHLETES]: { name: 'Deportistas', description: 'Registro, consulta, edición e impresión de deportistas.' },
 [APP_FEATURES.SOCIAL_WORK]: { name: 'Trabajo Social', description: 'Fichas sociales, caracterización, alertas, seguimientos y diagramas.' },
 [APP_FEATURES.CAMPAIGNS]: { name: 'Brigadas', description: 'Creación de brigadas, aplicación de tamizajes y resultados.' },
 [APP_FEATURES.INSTRUMENTS]: { name: 'Instrumentos', description: 'Edición, vista previa, aplicación e impresión de cuestionarios.' },
 [APP_FEATURES.REPORTS]: { name: 'Reportes', description: 'Indicadores, reportes poblacionales e individuales.' },
 [APP_FEATURES.CATALOGS]: { name: 'Catálogos', description: 'Programas, deportes, categorías y entrenadores.' },
 [APP_FEATURES.SYNC]: { name: 'Sincronización', description: 'Estado y resolución de cambios pendientes del dispositivo.' },
};

function FeatureSections({notify}:{notify:(s:string)=>void}) {
 const[items,setItems]=useState<FeatureVisibilityData[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[error,setError]=useState('');
 useEffect(()=>{api.featureVisibility().then(setItems).catch(reason=>setError(reason instanceof Error?reason.message:'No fue posible cargar las secciones.')).finally(()=>setLoading(false))},[]);
 async function toggle(item:FeatureVisibilityData){setBusy(item.key);setError('');try{const saved=await api.updateFeatureVisibility(item.key,!item.enabledForSocialWorker);setItems(current=>current.map(value=>value.key===saved.key?saved:value));notify(saved.enabledForSocialWorker?'Sección visible para Trabajo Social.':'Sección oculta para Trabajo Social.');window.dispatchEvent(new Event('socialapp:features-updated'))}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible actualizar la sección.')}finally{setBusy('')}}
 return <section className="mt-5"><h2 className="font-display text-3xl text-pine-900">Secciones para Trabajo Social</h2><p className="mt-2 max-w-3xl text-sm text-slate-500">Los cambios se aplican al menú, los accesos del inicio y las rutas directas del perfil Trabajo Social. Administración conserva acceso completo.</p>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{loading?<div className="card mt-5 p-10 text-center text-sm text-slate-500">Cargando secciones…</div>:<div className="mt-5 grid gap-4 md:grid-cols-2">{items.map(item=>{const label=featureLabels[item.key];return <article key={item.key} className="card flex items-center justify-between gap-4 p-5"><div className="flex items-start gap-3"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${item.enabledForSocialWorker?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{item.enabledForSocialWorker?<Eye size={20}/>:<EyeOff size={20}/>}</span><div><h3 className="font-semibold text-pine-900">{label.name}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{label.description}</p></div></div><button type="button" disabled={busy===item.key} onClick={()=>void toggle(item)} className={`min-h-10 shrink-0 rounded-xl px-4 text-sm font-bold ${item.enabledForSocialWorker?'border border-red-200 text-red-700 hover:bg-red-50':'bg-pine-700 text-white hover:bg-pine-800'}`}>{busy===item.key?'Guardando…':item.enabledForSocialWorker?'Ocultar':'Activar'}</button></article>})}</div>}</section>
}
function Users({data,reload,notify}:{data:AdminUserData[];reload:()=>Promise<void>;notify:(s:string)=>void}){const[open,setOpen]=useState(false);const[email,setEmail]=useState('');const[name,setName]=useState('');const[password,setPassword]=useState('');const[role,setRole]=useState('SOCIAL_WORKER');async function save(){await api.createUser({email,displayName:name,password,roles:[role]});notify('Usuario creado.');setOpen(false);await reload()}return <section className="mt-5"><div className="flex justify-between"><h2 className="font-display text-3xl text-pine-900">Usuarios</h2><button className="btn-primary px-4" onClick={()=>setOpen(!open)}><Plus size={17}/>Nuevo</button></div>{open&&<div className="card mt-5 grid gap-4 p-5 md:grid-cols-2"><input className="field" placeholder="Nombre completo" value={name} onChange={e=>setName(e.target.value)}/><input className="field" placeholder="Correo" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" className="field" placeholder="Contraseña temporal" value={password} onChange={e=>setPassword(e.target.value)}/><select className="field" value={role} onChange={e=>setRole(e.target.value)}><option value="SOCIAL_WORKER">Trabajo Social</option><option value="COACH">Entrenador</option><option value="COORDINATOR">Coordinador</option><option value="ADMIN">Administrador</option></select><button className="btn-primary md:col-span-2" onClick={()=>void save()}><Save size={17}/>Crear usuario</button></div>}<div className="mt-5 space-y-3">{data.map(u=><article key={u.id} className="card flex items-center justify-between gap-4 p-4"><div><p className="font-semibold text-pine-900">{u.displayName}</p><p className="text-xs text-slate-500">{u.email} · {u.roles.join(', ')}</p></div><select aria-label={`Estado de ${u.displayName}`} className="field max-w-40" value={u.status} onChange={async e=>{await api.updateUserStatus(u.id,e.target.value);await reload()}}><option value="ACTIVE">Activo</option><option value="INACTIVE">Inactivo</option><option value="LOCKED">Bloqueado</option></select></article>)}</div></section>}
function Catalogs({data,reload,notify}:{data:Overview['catalogs'];reload:()=>Promise<void>;notify:(s:string)=>void}){const[kind,setKind]=useState('programs');const[name,setName]=useState('');async function save(){await api.createCatalog(kind,name);setName('');notify('Catálogo actualizado.');await reload()}return <section className="mt-5"><h2 className="font-display text-3xl text-pine-900">Catálogos deportivos</h2><div className="card mt-5 flex flex-col gap-3 p-5 sm:flex-row"><select className="field" value={kind} onChange={e=>setKind(e.target.value)}><option value="programs">Programas</option><option value="sports">Deportes</option><option value="categories">Categorías</option><option value="coaches">Entrenadores</option></select><input className="field" placeholder="Nuevo nombre" value={name} onChange={e=>setName(e.target.value)}/><button className="btn-primary shrink-0" onClick={()=>void save()}><Plus size={17}/>Agregar</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{Object.entries(data).map(([key,items])=><article key={key} className="card p-5"><h3 className="font-semibold capitalize text-pine-900">{key}</h3><div className="mt-3 flex flex-wrap gap-2">{items.map(i=><span key={i.id} className="rounded-full bg-pine-50 px-3 py-2 text-xs font-semibold text-pine-700">{i.name}</span>)}</div></article>)}</div></section>}
function Rules({data,reload,notify}:{data:ConfigurableRuleData[];reload:()=>Promise<void>;notify:(s:string)=>void}){const[indicator,setIndicator]=useState('');const[field,setField]=useState('transportDifficulty');const[value,setValue]=useState('FREQUENTLY');async function save(){await api.saveRule({id:createId(),name:indicator,source:'SOCIOECONOMIC',field,operator:'EQUALS',expectedValue:value,indicator,level:'YELLOW',active:true});notify('Regla guardada sin cambiar el código fuente.');setIndicator('');await reload()}return <section className="mt-5"><h2 className="font-display text-3xl text-pine-900">Motor de reglas</h2><div className="card mt-5 grid gap-4 p-5 md:grid-cols-2"><input className="field" placeholder="Nombre e indicador" value={indicator} onChange={e=>setIndicator(e.target.value)}/><input className="field" placeholder="Campo" value={field} onChange={e=>setField(e.target.value)}/><input className="field" placeholder="Valor esperado" value={value} onChange={e=>setValue(e.target.value)}/><button className="btn-primary" onClick={()=>void save()}><ShieldCheck size={17}/>Crear regla</button></div><div className="mt-5 space-y-3">{data.map(r=><article key={r.id} className="card p-4"><p className="font-semibold text-pine-900">{r.name}</p><p className="mt-1 text-xs text-slate-500">{r.source}.{r.field} {r.operator} {r.expectedValue} → {r.level}</p><p className="mt-2 text-sm">{r.indicator}</p></article>)}</div></section>}
function Instruments({data,reload,notify}:{data:Overview['instruments'];reload:()=>Promise<void>;notify:(s:string)=>void}){const[name,setName]=useState('');const[prompt,setPrompt]=useState('');async function save(){await api.saveInstrument({id:createId(),name,version:1,active:true,questions:[{id:createId(),dimension:'General',prompt,type:'YES_NO',options:['Sí','No'],required:true}]});notify('Instrumento versionado creado.');setName('');setPrompt('');await reload()}return <section className="mt-5"><h2 className="font-display text-3xl text-pine-900">Instrumentos configurables</h2><div className="card mt-5 grid gap-4 p-5 md:grid-cols-2"><input className="field" placeholder="Nombre del instrumento" value={name} onChange={e=>setName(e.target.value)}/><input className="field" placeholder="Primera pregunta" value={prompt} onChange={e=>setPrompt(e.target.value)}/><button className="btn-primary md:col-span-2" onClick={()=>void save()}><BookOpenCheck size={17}/>Crear instrumento v1</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{data.map(i=><article key={i.id} className="card p-5"><p className="font-semibold text-pine-900">{i.name} v{i.version}</p><p className="mt-2 text-sm text-slate-500">{i.questions.length} preguntas</p></article>)}</div></section>}
function Audit({data}:{data:AuditLogData[]}){return <section className="mt-5"><div className="flex items-center gap-3"><RefreshCw className="text-pine-600"/><h2 className="font-display text-3xl text-pine-900">Auditoría</h2></div><div className="card mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-pine-50 text-xs uppercase text-pine-700"><tr><th className="p-4">Fecha</th><th className="p-4">Usuario</th><th className="p-4">Acción</th><th className="p-4">Recurso</th><th className="p-4">Resultado</th></tr></thead><tbody>{data.map(i=><tr key={i.id} className="border-t border-slate-100"><td className="p-4">{new Date(i.createdAt).toLocaleString('es-CO')}</td><td className="p-4">{i.actorName||'Sistema'}</td><td className="p-4">{i.action}</td><td className="p-4">{i.resourceType||'—'}</td><td className="p-4">{i.outcome}</td></tr>)}</tbody></table></div></section>}
