import { BookOpenCheck, CalendarDays, CheckCircle2, MapPin, Plus, Search, ShieldCheck, UsersRound, WifiOff } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { PERMISSIONS, type CampaignStatus, type ScreeningCampaignData } from '@socialapp/shared';
import { useAuth } from '../features/auth/useAuth';
import { loadCampaigns } from '../features/work/work-repository';
import { useConnection } from '../hooks/useConnection';

export function CampaignsPage() {
  const { can } = useAuth();
  const online = useConnection();
  const [items, setItems] = useState<ScreeningCampaignData[]>([]);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState<'ALL' | CampaignStatus>('ALL');
  useEffect(() => { loadCampaigns().then(setItems); }, [online]);
  const totals = useMemo(() => ({ participants: items.reduce((total, item) => total + item.participants.length, 0), completed: items.reduce((total, item) => total + item.participants.filter((participant) => participant.status === 'COMPLETED').length, 0), active: items.filter((item) => item.status === 'ACTIVE').length }), [items]);
  const visible = useMemo(() => { const term = search.trim().toLocaleLowerCase('es'); return items.filter((item) => (status === 'ALL' || item.status === status) && (!term || `${item.name} ${item.place} ${item.sportsProgramName ?? ''} ${item.sportName ?? ''}`.toLocaleLowerCase('es').includes(term))); }, [items, search, status]);
  return <div>
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold text-coral-600">Trabajo de campo</p><h1 className="font-display text-4xl text-pine-900">Brigadas y tamizajes</h1><p className="mt-2 text-sm text-slate-500">Organiza jornadas, asigna población, retoma avances y consulta resultados incluso sin conexión.</p></div>{can(PERMISSIONS.SCREENING_WRITE) && <div className="flex flex-wrap gap-2"><Link className="btn-secondary" to="/instrumentos"><BookOpenCheck size={18}/> Instrumentos</Link><Link className="btn-primary" to="/brigadas/nueva"><Plus size={18}/> Nueva brigada</Link></div>}</div>
    {!online && <div className="mt-5 flex items-center gap-3 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800"><WifiOff size={18}/> Modo sin conexión: se muestran y guardan los datos disponibles en este dispositivo.</div>}
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={<ShieldCheck/>} value={items.length} label="Brigadas"/><Kpi icon={<CalendarDays/>} value={totals.active} label="En curso"/><Kpi icon={<UsersRound/>} value={totals.participants} label="Participantes"/><Kpi icon={<CheckCircle2/>} value={totals.completed} label="Tamizajes completados"/></div>
    <section className="card mt-6 grid gap-3 p-4 sm:grid-cols-[1fr_220px]"><label className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><span className="sr-only">Buscar brigada</span><input className="field pl-11" placeholder="Buscar por nombre, lugar, programa o deporte…" value={search} onChange={(event) => setSearch(event.target.value)}/></label><select aria-label="Filtrar brigadas por estado" className="field" value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option value="ALL">Todos los estados</option><option value="PLANNED">Planeadas</option><option value="ACTIVE">En curso</option><option value="COMPLETED">Finalizadas</option></select></section>
    <div className="mt-5 grid gap-5 lg:grid-cols-2">{visible.length === 0 && <div className="card col-span-full p-10 text-center text-sm text-slate-500">No hay brigadas que coincidan con la búsqueda.</div>}{visible.map((item) => { const completed = item.participants.filter((participant) => participant.status === 'COMPLETED').length; const inProgress = item.participants.filter((participant) => participant.status === 'IN_PROGRESS').length; return <Link key={item.id} to={`/brigadas/${item.id}`} className="card p-5 transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-pine-50 px-3 py-1 text-xs font-bold text-pine-700">{item.status === 'ACTIVE' ? 'En curso' : item.status === 'COMPLETED' ? 'Finalizada' : 'Planeada'}</span>{item.syncStatus && item.syncStatus !== 'synced' && <span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">Sincronización pendiente</span>}</div><h2 className="mt-3 font-display text-2xl text-pine-900">{item.name}</h2></div><div className="grid h-11 w-11 place-items-center rounded-xl bg-coral-100 text-coral-600"><CalendarDays/></div></div><p className="mt-4 flex items-center gap-2 text-sm text-slate-500"><MapPin size={17}/>{item.place} · {item.date}</p><p className="mt-2 text-sm text-slate-500">{item.sportsProgramName || 'Todos los programas'} · {item.sportName || 'Todos los deportes'}</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-pine-600" style={{ width: `${item.participants.length ? completed / item.participants.length * 100 : 0}%` }}/></div><p className="mt-2 text-xs font-semibold text-slate-500">{completed} completados · {inProgress} en proceso · {item.participants.length - completed - inProgress} pendientes</p></Link>; })}</div>
  </div>;
}

function Kpi({ icon, value, label }: { icon: React.ReactNode; value: number; label: string }) { return <article className="card flex items-center gap-4 p-5"><div className="grid h-12 w-12 place-items-center rounded-xl bg-pine-50 text-pine-700">{icon}</div><div><p className="text-2xl font-bold text-pine-900">{value}</p><p className="text-xs text-slate-500">{label}</p></div></article>; }
