import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Save } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import type { AthleteRecord, ScreeningCampaignInput, ScreeningInstrumentData, SportsCatalogs } from '@socialapp/shared';
import { useAuth } from '../features/auth/useAuth';
import { loadAthletes, loadCatalogs } from '../features/athletes/athlete-repository';
import { loadInstruments, saveCampaignOffline } from '../features/work/work-repository';

export function CampaignFormPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const [athletes, setAthletes] = useState<AthleteRecord[]>([]); const [catalogs, setCatalogs] = useState<SportsCatalogs>(); const [instruments, setInstruments] = useState<ScreeningInstrumentData[]>([]); const [selected, setSelected] = useState<string[]>([]);
  const [values, setValues] = useState({ name: '', date: new Date().toISOString().slice(0,10), place: '', programId: '', sportId: '', instrumentId: '' });
  useEffect(() => { Promise.all([loadAthletes(), loadCatalogs(), loadInstruments()]).then(([people,cats,forms]) => { setAthletes(people); setCatalogs(cats); setInstruments(forms); if (forms[0]) setValues((v) => ({ ...v, instrumentId: forms[0]!.id })); }); }, []);
  const filtered = useMemo(() => athletes.filter((item) => (!values.programId || item.sportsProgramId === values.programId) && (!values.sportId || item.sportId === values.sportId)), [athletes, values.programId, values.sportId]);
  async function save() { const instrument = instruments.find((item) => item.id === values.instrumentId); if (!values.name || !values.place || !instrument || selected.length === 0) return; const input: ScreeningCampaignInput = { id: crypto.randomUUID(), name: values.name, date: values.date, place: values.place, sportsProgramId: values.programId || null, sportId: values.sportId || null, instrumentId: instrument.id, professionalName: user?.displayName ?? 'Trabajo Social', athleteIds: selected, status: 'ACTIVE', version: 0 }; await saveCampaignOffline(input, instrument, Object.fromEntries(athletes.map((item) => [item.id, `${item.firstNames} ${item.lastNames}`]))); navigate(`/brigadas/${input.id}`); }
  return <div className="mx-auto max-w-5xl"><Link to="/brigadas" className="inline-flex items-center gap-2 text-sm font-semibold text-pine-700"><ArrowLeft size={17}/> Volver a brigadas</Link><h1 className="mt-5 font-display text-4xl text-pine-900">Nueva brigada</h1><p className="mt-2 text-sm text-slate-500">Los deportistas e instrumentos quedarán disponibles en el dispositivo para la jornada.</p>
    <section className="card mt-6 grid gap-5 p-5 md:grid-cols-2 md:p-7"><Field label="Nombre de la brigada"><input className="field" value={values.name} onChange={(e) => setValues({...values,name:e.target.value})}/></Field><Field label="Fecha"><input type="date" className="field" value={values.date} onChange={(e) => setValues({...values,date:e.target.value})}/></Field><Field label="Lugar"><input className="field" value={values.place} onChange={(e) => setValues({...values,place:e.target.value})}/></Field><Field label="Instrumento"><select className="field" value={values.instrumentId} onChange={(e) => setValues({...values,instrumentId:e.target.value})}>{instruments.map((item) => <option key={item.id} value={item.id}>{item.name} v{item.version}</option>)}</select></Field><Field label="Programa"><select className="field" value={values.programId} onChange={(e) => setValues({...values,programId:e.target.value})}><option value="">Todos</option>{catalogs?.programs.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Deporte"><select className="field" value={values.sportId} onChange={(e) => setValues({...values,sportId:e.target.value})}><option value="">Todos</option>{catalogs?.sports.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></section>
    <section className="card mt-6 p-5 md:p-7"><div className="flex items-center justify-between"><div><h2 className="font-display text-2xl text-pine-900">Seleccionar deportistas</h2><p className="text-sm text-slate-500">{selected.length} seleccionados</p></div><button className="text-sm font-bold text-pine-700" onClick={() => setSelected(selected.length === filtered.length ? [] : filtered.map((item) => item.id))}>{selected.length === filtered.length ? 'Quitar todos' : 'Seleccionar todos'}</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{filtered.map((item) => <label key={item.id} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-4"><input type="checkbox" className="h-5 w-5 accent-pine-700" checked={selected.includes(item.id)} onChange={() => setSelected((current) => current.includes(item.id) ? current.filter((id) => id !== item.id) : [...current,item.id])}/><div><p className="font-semibold text-pine-900">{item.firstNames} {item.lastNames}</p><p className="text-xs text-slate-500">{item.internalCode} · {item.sportName}</p></div></label>)}</div></section>
    <button className="btn-primary mt-6 w-full" onClick={() => void save()}><Save size={18}/> Guardar e iniciar brigada</button>
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span>{children}</label>; }
