import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, CheckCircle2, MapPin, Plus, ShieldCheck, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { ScreeningCampaignData } from '@socialapp/shared';
import { loadCampaigns } from '../features/work/work-repository';

export function CampaignsPage() {
  const [items, setItems] = useState<ScreeningCampaignData[]>([]);
  useEffect(() => { loadCampaigns().then(setItems); }, []);
  const totals = useMemo(() => ({ participants: items.reduce((n,i) => n + i.participants.length, 0), completed: items.reduce((n,i) => n + i.participants.filter((p) => p.status === 'COMPLETED').length, 0) }), [items]);
  return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold text-coral-600">Trabajo de campo</p><h1 className="font-display text-4xl text-pine-900">Brigadas y tamizajes</h1><p className="mt-2 text-sm text-slate-500">Organiza jornadas, asigna población y aplica instrumentos incluso sin conexión.</p></div><Link className="btn-primary" to="/brigadas/nueva"><Plus size={18}/> Nueva brigada</Link></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-3"><Kpi icon={<ShieldCheck/>} value={items.length} label="Brigadas"/><Kpi icon={<UsersRound/>} value={totals.participants} label="Participantes"/><Kpi icon={<CheckCircle2/>} value={totals.completed} label="Tamizajes completados"/></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-2">{items.length === 0 && <div className="card col-span-full p-10 text-center text-sm text-slate-500">Aún no hay brigadas. Crea la primera para iniciar una jornada de campo.</div>}{items.map((item) => { const completed = item.participants.filter((p) => p.status === 'COMPLETED').length; return <Link key={item.id} to={`/brigadas/${item.id}`} className="card p-5 transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-start justify-between gap-3"><div><span className="rounded-full bg-pine-50 px-3 py-1 text-xs font-bold text-pine-700">{item.status === 'ACTIVE' ? 'En curso' : item.status === 'COMPLETED' ? 'Finalizada' : 'Planeada'}</span><h2 className="mt-3 font-display text-2xl text-pine-900">{item.name}</h2></div><div className="grid h-11 w-11 place-items-center rounded-xl bg-coral-100 text-coral-600"><CalendarDays/></div></div><p className="mt-4 flex items-center gap-2 text-sm text-slate-500"><MapPin size={17}/>{item.place} · {item.date}</p><p className="mt-2 text-sm text-slate-500">{item.sportsProgramName || 'Todos los programas'} · {item.sportName || 'Todos los deportes'}</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-pine-600" style={{ width: `${item.participants.length ? completed / item.participants.length * 100 : 0}%` }}/></div><p className="mt-2 text-xs font-semibold text-slate-500">{completed} de {item.participants.length} completados</p></Link>; })}</div>
  </div>;
}
function Kpi({ icon, value, label }: { icon: React.ReactNode; value: number; label: string }) { return <article className="card flex items-center gap-4 p-5"><div className="grid h-12 w-12 place-items-center rounded-xl bg-pine-50 text-pine-700">{icon}</div><div><p className="text-2xl font-bold text-pine-900">{value}</p><p className="text-xs text-slate-500">{label}</p></div></article>; }
