import { useEffect, useState } from 'react';
import { ArrowLeft, Printer } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import type { AthleteRecord, AthleteWorkspace } from '@socialapp/shared';
import { api } from '../lib/api';

type IndividualReport = { athlete: AthleteRecord; workspace: AthleteWorkspace; generatedAt: string };
export function IndividualReportPage() {
  const { id = '' } = useParams(); const [report,setReport]=useState<IndividualReport>();
  useEffect(()=>{api.individualReport(id).then((value)=>setReport(value as IndividualReport))},[id]);
  async function print(){await api.auditExport('IndividualReport',id);window.print()}
  if(!report)return <div className="p-12 text-center text-sm text-slate-500">Preparando reporte individual…</div>;
  const {athlete,workspace}=report;
  return <div className="mx-auto max-w-5xl bg-white p-5 md:p-8"><div className="flex items-center justify-between print:hidden"><Link to={`/deportistas/${id}`} className="inline-flex items-center gap-2 text-sm font-semibold text-pine-700"><ArrowLeft size={17}/>Volver al expediente</Link><button className="btn-primary" onClick={()=>void print()}><Printer size={17}/>PDF / Imprimir</button></div><header className="mt-6 border-b-2 border-pine-800 pb-6"><p className="text-sm font-bold uppercase tracking-wider text-coral-600">Reporte individual de Trabajo Social</p><h1 className="mt-2 font-display text-4xl text-pine-900">{athlete.firstNames} {athlete.lastNames}</h1><p className="mt-2 text-sm text-slate-500">{athlete.internalCode} · {athlete.age} años · {athlete.sportName} · {athlete.sportsProgramName}</p></header>
    <ReportSection title="Información general"><Grid><Item label="Documento" value={athlete.documentNumber||'No informado'}/><Item label="Municipio" value={athlete.municipality}/><Item label="Zona" value={athlete.zone==='URBAN'?'Urbana':'Rural'}/><Item label="Acudiente" value={athlete.guardian.name}/><Item label="Teléfono" value={athlete.guardian.phone}/><Item label="Escolarización" value={athlete.currentlyEnrolled?`${athlete.schoolName||''} · ${athlete.schoolGrade||''}`:'No escolarizado'}/></Grid></ReportSection>
    <ReportSection title="Información familiar y redes"><p className="text-sm leading-6 text-slate-600">{athlete.hasSocialRecord?'Ficha social registrada. Consulte el instrumento versionado para respuestas completas.':'Ficha social pendiente.'}</p><p className="mt-2 text-sm text-slate-600">Familiograma: {workspace.genogram?'registrado':'pendiente'} · Ecomapa: {workspace.ecomap?'registrado':'pendiente'}</p></ReportSection>
    <ReportSection title="Caracterización socioeconómica">{workspace.socioeconomicAssessment?<Grid><Item label="Vivienda" value={workspace.socioeconomicAssessment.housingType}/><Item label="Transporte" value={workspace.socioeconomicAssessment.transportMode}/><Item label="Dificultad de transporte" value={workspace.socioeconomicAssessment.transportDifficulty}/><Item label="Seguridad alimentaria" value={workspace.socioeconomicAssessment.foodReduction}/><Item label="Ingreso aproximado" value={workspace.socioeconomicAssessment.incomeRange}/><Item label="Valoración profesional" value={workspace.socioeconomicAssessment.professionalAssessment||'Sin valoración registrada'}/></Grid>:<p className="text-sm text-slate-500">Caracterización pendiente.</p>}</ReportSection>
    <ReportSection title="Indicadores, seguimiento y valoración"><Grid><Item label="Alertas pendientes" value={String(workspace.alerts.filter(a=>a.status==='PENDING').length)}/><Item label="Seguimientos abiertos" value={String(workspace.followUps.filter(f=>f.status!=='CLOSED').length)}/><Item label="Observaciones" value={String(workspace.observations.length)}/></Grid><div className="mt-5 space-y-3">{workspace.alerts.map(a=><div key={a.id} className="rounded-xl border p-4"><p className="text-xs font-bold text-slate-400">INDICADOR AUTOMÁTICO</p><p className="mt-1 font-semibold">{a.automaticIndicator}</p><p className="mt-2 text-sm text-slate-600"><strong>Valoración profesional:</strong> {a.professionalAssessment||'Pendiente'}</p></div>)}</div></ReportSection>
    <ReportSection title="Historial"><div className="space-y-3">{workspace.timeline.map(e=><div key={e.id} className="border-l-2 border-pine-200 pl-4"><p className="text-xs text-slate-400">{new Date(e.date).toLocaleDateString('es-CO')}</p><p className="font-semibold">{e.title}</p>{e.detail&&<p className="text-sm text-slate-500">{e.detail}</p>}</div>)}</div></ReportSection>
    <footer className="mt-8 border-t pt-4 text-xs text-slate-400">Generado el {new Date(report.generatedAt).toLocaleString('es-CO')}. Este documento apoya la organización de Trabajo Social y no constituye diagnóstico clínico.</footer>
  </div>;
}
function ReportSection({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-7 break-inside-avoid"><h2 className="font-display text-2xl text-pine-900">{title}</h2><div className="mt-4">{children}</div></section>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{children}</div>}
function Item({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-1 text-sm text-slate-700">{value}</p></div>}
