import { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, Printer, Sparkles } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { PERMISSIONS, type AiRiskReportData, type AthleteRecord, type AthleteWorkspace } from '@socialapp/shared';
import { useAuth } from '../features/auth/useAuth';
import { api } from '../lib/api';

type IndividualReport = { athlete: AthleteRecord; workspace: AthleteWorkspace; aiReports: AiRiskReportData[]; generatedAt: string };
export function IndividualReportPage() {
  const { id = '' } = useParams(); const { can } = useAuth(); const [report,setReport]=useState<IndividualReport>();
  const [generating,setGenerating]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{Promise.all([api.individualReport(id),api.listAiRiskReports(id)]).then(([value,aiReports])=>setReport({...value as Omit<IndividualReport,'aiReports'>,aiReports})).catch((reason)=>setError(reason instanceof Error?reason.message:'No fue posible preparar el reporte.'))},[id]);
  async function print(){await api.auditExport('IndividualReport',id);window.print()}
  async function generate(){setGenerating(true);setError('');try{const generated=await api.generateAiRiskReport(id);setReport((current)=>current?{...current,aiReports:[generated,...current.aiReports]}:current)}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible generar el análisis.')}finally{setGenerating(false)}}
  async function review(item:AiRiskReportData){setError('');try{const reviewed=await api.reviewAiRiskReport(item.id);setReport((current)=>current?{...current,aiReports:current.aiReports.map((value)=>value.id===reviewed.id?reviewed:value)}:current)}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible validar el informe.')}}
  if(!report)return <div className="p-12 text-center text-sm text-slate-500">{error||'Preparando reporte individual…'}</div>;
  const {athlete,workspace}=report;
  return <div className="mx-auto max-w-5xl bg-white p-5 md:p-8"><div className="flex flex-wrap items-center justify-between gap-3 print:hidden"><Link to={`/deportistas/${id}`} className="inline-flex items-center gap-2 text-sm font-semibold text-pine-700"><ArrowLeft size={17}/>Volver al expediente</Link><div className="flex flex-wrap gap-2">{can(PERMISSIONS.SOCIAL_RECORD_WRITE)&&<button className="btn-secondary" disabled={generating} onClick={()=>void generate()}><Sparkles size={17}/>{generating?'Analizando…':'Generar análisis de riesgo'}</button>}<button className="btn-primary" onClick={()=>void print()}><Printer size={17}/>PDF / Imprimir</button></div></div>{error&&<div role="alert" className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<header className="mt-6 border-b-2 border-pine-800 pb-6"><p className="text-sm font-bold uppercase tracking-wider text-coral-600">Reporte individual de Trabajo Social</p><h1 className="mt-2 font-display text-4xl text-pine-900">{athlete.firstNames} {athlete.lastNames}</h1><p className="mt-2 text-sm text-slate-500">{athlete.internalCode} · {athlete.age} años · {athlete.sportName} · {athlete.sportsProgramName}</p></header>
    <ReportSection title="Análisis asistido de riesgo">{report.aiReports.length===0?<div className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">Aún no se ha generado un análisis. Completa la información disponible y usa “Generar análisis de riesgo”.</div>:<div className="space-y-5">{report.aiReports.map((item,index)=><AiReportCard key={item.id} item={item} latest={index===0} canReview={can(PERMISSIONS.SOCIAL_RECORD_WRITE)} onReview={()=>void review(item)}/>)}</div>}<p className="mt-3 text-xs leading-5 text-slate-500">La información se envía seudonimizada. Este análisis apoya la priorización y no reemplaza la valoración profesional ni constituye diagnóstico.</p></ReportSection>
    <ReportSection title="Información general"><Grid><Item label="Documento" value={athlete.documentNumber||'No informado'}/><Item label="Municipio" value={athlete.municipality}/><Item label="Zona" value={athlete.zone==='UNSPECIFIED'?'Sin informar':athlete.zone==='URBAN'?'Urbana':'Rural'}/><Item label="Acudiente" value={athlete.guardian.name}/><Item label="Teléfono" value={athlete.guardian.phone}/><Item label="Escolarización" value={athlete.currentlyEnrolled?`${athlete.schoolName||''} · ${athlete.schoolGrade||''}`:'No escolarizado'}/></Grid></ReportSection>
    <ReportSection title="Información familiar y redes"><p className="text-sm leading-6 text-slate-600">{athlete.hasSocialRecord?'Ficha social registrada. Consulte el instrumento versionado para respuestas completas.':'Ficha social pendiente.'}</p><p className="mt-2 text-sm text-slate-600">Familiograma: {workspace.genogram?'registrado':'pendiente'} · Ecomapa: {workspace.ecomap?'registrado':'pendiente'}</p></ReportSection>
    <ReportSection title="Caracterización socioeconómica">{workspace.socioeconomicAssessment?<Grid><Item label="Vivienda" value={workspace.socioeconomicAssessment.housingType}/><Item label="Transporte" value={workspace.socioeconomicAssessment.transportMode}/><Item label="Dificultad de transporte" value={workspace.socioeconomicAssessment.transportDifficulty}/><Item label="Seguridad alimentaria" value={workspace.socioeconomicAssessment.foodReduction}/><Item label="Ingreso aproximado" value={workspace.socioeconomicAssessment.incomeRange}/><Item label="Valoración profesional" value={workspace.socioeconomicAssessment.professionalAssessment||'Sin valoración registrada'}/></Grid>:<p className="text-sm text-slate-500">Caracterización pendiente.</p>}</ReportSection>
    <ReportSection title="Indicadores, seguimiento y valoración"><Grid><Item label="Alertas pendientes" value={String(workspace.alerts.filter(a=>a.status==='PENDING').length)}/><Item label="Seguimientos abiertos" value={String(workspace.followUps.filter(f=>f.status!=='CLOSED').length)}/><Item label="Observaciones" value={String(workspace.observations.length)}/></Grid><div className="mt-5 space-y-3">{workspace.alerts.map(a=><div key={a.id} className="rounded-xl border p-4"><p className="text-xs font-bold text-slate-400">INDICADOR AUTOMÁTICO</p><p className="mt-1 font-semibold">{a.automaticIndicator}</p><p className="mt-2 text-sm text-slate-600"><strong>Valoración profesional:</strong> {a.professionalAssessment||'Pendiente'}</p></div>)}</div></ReportSection>
    <ReportSection title="Historial"><div className="space-y-3">{workspace.timeline.map(e=><div key={e.id} className="border-l-2 border-pine-200 pl-4"><p className="text-xs text-slate-400">{new Date(e.date).toLocaleDateString('es-CO')}</p><p className="font-semibold">{e.title}</p>{e.detail&&<p className="text-sm text-slate-500">{e.detail}</p>}</div>)}</div></ReportSection>
    <footer className="mt-8 border-t pt-4 text-xs text-slate-400">Generado el {new Date(report.generatedAt).toLocaleString('es-CO')}. Este documento apoya la organización de Trabajo Social y no constituye diagnóstico clínico.</footer>
  </div>;
}
const riskLabels={LOW:'Bajo',MEDIUM:'Medio',HIGH:'Alto',CRITICAL:'Crítico'} as const;
const riskStyles={LOW:'bg-emerald-50 text-emerald-800',MEDIUM:'bg-amber-50 text-amber-800',HIGH:'bg-orange-50 text-orange-800',CRITICAL:'bg-red-50 text-red-800'} as const;
function AiReportCard({item,latest,canReview,onReview}:{item:AiRiskReportData;latest:boolean;canReview:boolean;onReview:()=>void}){return <article className="rounded-2xl border border-slate-200 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-bold ${riskStyles[item.riskLevel]}`}>Riesgo {riskLabels[item.riskLevel]}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">{item.status==='REVIEWED'?'Revisado por profesional':'Borrador generado'}</span>{latest&&<span className="text-xs font-semibold text-pine-700">Más reciente</span>}</div>{canReview&&item.status==='DRAFT'&&<button className="btn-secondary min-h-9 px-3 py-1 text-xs print:hidden" onClick={onReview}><CheckCircle2 size={15}/>Marcar revisado</button>}</div><p className="mt-4 text-sm leading-6 text-slate-700">{item.summary}</p><div className="mt-5 grid gap-5 md:grid-cols-2"><ReportList title="Factores de riesgo" items={item.riskFactors}/><ReportList title="Factores protectores" items={item.protectiveFactors}/><ReportList title="Recomendaciones" items={item.recommendations}/><ReportList title="Acciones urgentes" items={item.urgentActions}/></div><div className="mt-4 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-600"><strong>Limitaciones:</strong> {item.limitations}</div><p className="mt-3 text-xs text-slate-400">Generado {new Date(item.generatedAt).toLocaleString('es-CO')} · {item.model}</p></article>}
function ReportList({title,items}:{title:string;items:string[]}){return <div><h3 className="text-xs font-bold uppercase tracking-wide text-slate-400">{title}</h3>{items.length?<ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">{items.map((value,index)=><li key={index}>{value}</li>)}</ul>:<p className="mt-2 text-sm text-slate-400">Ninguno identificado.</p>}</div>}
function ReportSection({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-7 break-inside-avoid"><h2 className="font-display text-2xl text-pine-900">{title}</h2><div className="mt-4">{children}</div></section>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{children}</div>}
function Item({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-1 text-sm text-slate-700">{value}</p></div>}
