import { useEffect, useState } from 'react';
import { Download, FileDown, Printer } from 'lucide-react';
import type { ReportPopulationData, SportsCatalogs } from '@socialapp/shared';
import { loadCatalogs } from '../features/athletes/athlete-repository';
import { api } from '../lib/api';

export function ReportsPage() {
  const [report,setReport] = useState<ReportPopulationData>(); const [catalogs,setCatalogs] = useState<SportsCatalogs>(); const [programId,setProgramId]=useState(''); const [sportId,setSportId]=useState('');
  async function load() { setReport(await api.populationReport(Object.fromEntries(Object.entries({programId,sportId}).filter(([,v])=>v)))); }
  useEffect(() => { loadCatalogs().then(setCatalogs); api.populationReport().then(setReport); }, []);
  async function printReport() { await api.auditExport('PopulationReport'); window.print(); }
  async function exportCsv() { if (!report) return; await api.auditExport('PopulationReport'); const rows: (string|number)[][] = [['Indicador','Valor'],['Deportistas',report.athletes],['Fichas sociales',report.socialRecords],['Caracterizaciones',report.socioeconomicAssessments],['Tamizajes',report.screenings],['Seguimientos abiertos',report.openFollowUps],['Alertas pendientes',report.pendingAlerts],...report.programs.map((item)=>[`Programa: ${item.name}`,item.count]),...report.sports.map((item)=>[`Deporte: ${item.name}`,item.count])]; const csv='\uFEFF'+rows.map((row)=>row.map((cell)=>`"${String(cell).replaceAll('"','""')}"`).join(',')).join('\n'); const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})); const a=document.createElement('a'); a.href=url;a.download='reporte-poblacional.csv';a.click();URL.revokeObjectURL(url); }
  const pct = (value:number) => report?.athletes ? Math.round(value/report.athletes*100) : 0;
  return <div className="print:bg-white"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold text-coral-600">Indicadores y exportaciones</p><h1 className="font-display text-4xl text-pine-900">Reportes</h1><p className="mt-2 text-sm text-slate-500">Información consolidada sin exponer valoraciones sensibles.</p></div><div className="flex gap-3 print:hidden"><button className="btn-secondary" onClick={() => void exportCsv()}><Download size={17}/> Excel/CSV</button><button className="btn-primary" onClick={() => void printReport()}><Printer size={17}/> PDF / Imprimir</button></div></div>
    <section className="card mt-6 grid gap-4 p-5 sm:grid-cols-3 print:hidden"><select aria-label="Filtrar por programa" className="field" value={programId} onChange={(e)=>setProgramId(e.target.value)}><option value="">Todos los programas</option>{catalogs?.programs.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Filtrar por deporte" className="field" value={sportId} onChange={(e)=>setSportId(e.target.value)}><option value="">Todos los deportes</option>{catalogs?.sports.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="btn-primary" onClick={() => void load()}><FileDown size={17}/> Aplicar filtros</button></section>
    {!report ? <p className="p-12 text-center text-sm text-slate-500">Calculando indicadores…</p> : <><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric value={report.athletes} label="Deportistas"/><Metric value={`${pct(report.socialRecords)}%`} label="Con ficha social"/><Metric value={`${pct(report.socioeconomicAssessments)}%`} label="Caracterizados"/><Metric value={report.screenings} label="Tamizajes"/><Metric value={report.openFollowUps} label="Seguimientos abiertos"/><Metric value={report.highPriorityFollowUps} label="Prioritarios"/><Metric value={report.pendingAlerts} label="Alertas pendientes"/><Metric value={report.socialRecords} label="Fichas realizadas"/></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><Distribution title="Distribución por programa" items={report.programs}/><Distribution title="Distribución por deporte" items={report.sports}/><Distribution title="Distribución por edades" items={report.ageGroups}/><Distribution title="Principales barreras" items={report.barriers}/></div><p className="mt-6 text-xs text-slate-400">Generado: {new Date(report.generatedAt).toLocaleString('es-CO')}</p></>}
  </div>;
}
function Metric({value,label}:{value:string|number;label:string}){return <article className="card p-5"><p className="font-display text-3xl text-pine-900">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></article>}
function Distribution({title,items}:{title:string;items:{name:string;count:number}[]}){const max=Math.max(1,...items.map(i=>i.count));return <article className="card p-5"><h2 className="font-display text-2xl text-pine-900">{title}</h2><div className="mt-5 space-y-4">{items.length===0&&<p className="text-sm text-slate-400">Sin datos para este filtro.</p>}{items.map((item)=><div key={item.name}><div className="flex justify-between text-sm"><span>{item.name}</span><strong>{item.count}</strong></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-pine-600" style={{width:`${item.count/max*100}%`}}/></div></div>)}</div></article>}
