import { useEffect, useState } from 'react';
import { ArrowLeft, Check } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import type { ScreeningCampaignData } from '@socialapp/shared';
import { loadCampaigns, saveScreeningOffline } from '../features/work/work-repository';

export function ScreeningFormPage() {
  const { id = '', athleteId = '' } = useParams(); const navigate = useNavigate(); const [campaign, setCampaign] = useState<ScreeningCampaignData>(); const [step, setStep] = useState(0); const [responses, setResponses] = useState<Record<string, unknown>>({});
  useEffect(() => { loadCampaigns().then((items) => { const item = items.find((campaign) => campaign.id === id); setCampaign(item); const existing = item?.participants.find((p) => p.athleteId === athleteId); if (existing) setResponses(existing.responses); }); }, [id, athleteId]);
  if (!campaign) return <div className="p-12 text-center text-sm text-slate-500">Abriendo instrumento…</div>;
  const currentCampaign = campaign; const question = currentCampaign.instrument.questions[step]; const person = currentCampaign.participants.find((p) => p.athleteId === athleteId); if (!question || !person) return null;
  const value = responses[question.id];
  async function next() { if (question!.required && (value === undefined || value === '')) return; if (step < currentCampaign.instrument.questions.length - 1) setStep(step + 1); else { await saveScreeningOffline(id, athleteId, responses); navigate(`/brigadas/${id}`); } }
  return <div className="mx-auto max-w-3xl"><Link to={`/brigadas/${id}`} className="inline-flex items-center gap-2 text-sm font-semibold text-pine-700"><ArrowLeft size={17}/> Volver a la brigada</Link><div className="mt-5"><p className="text-sm font-bold text-coral-600">{campaign.instrument.name} v{campaign.instrument.version}</p><h1 className="font-display text-4xl text-pine-900">{person.athleteName}</h1><p className="mt-2 text-sm text-slate-500">Pregunta {step+1} de {campaign.instrument.questions.length} · {question.dimension}</p></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-pine-100"><div className="h-full bg-coral-500" style={{width:`${(step+1)/campaign.instrument.questions.length*100}%`}}/></div>
    <section className="card mt-6 p-6 md:p-9"><h2 className="font-display text-3xl leading-tight text-pine-900">{question.prompt}</h2><div className="mt-7 grid gap-3">{question.type === 'TEXT' ? <textarea className="field py-3" rows={5} value={String(value ?? '')} onChange={(e) => setResponses({...responses,[question.id]:e.target.value})}/> : question.type === 'NUMBER' ? <input type="number" className="field" value={String(value ?? '')} onChange={(e) => setResponses({...responses,[question.id]:Number(e.target.value)})}/> : question.options.map((option) => <label key={option} className="flex min-h-14 cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-4"><input type={question.type === 'MULTIPLE_CHOICE' ? 'checkbox' : 'radio'} name={question.id} className="h-5 w-5 accent-pine-700" checked={question.type === 'MULTIPLE_CHOICE' ? Array.isArray(value) && value.includes(option) : value === option} onChange={() => setResponses({...responses,[question.id]:question.type === 'MULTIPLE_CHOICE' ? (Array.isArray(value) && value.includes(option) ? value.filter((v) => v !== option) : [...(Array.isArray(value) ? value : []),option]) : option})}/><span className="font-medium">{option}</span></label>)}</div></section>
    <div className="mt-5 flex justify-between"><button className="btn-secondary" disabled={step===0} onClick={() => setStep(step-1)}>Anterior</button><button className="btn-primary" onClick={() => void next()}>{step === campaign.instrument.questions.length-1 ? <><Check size={18}/> Finalizar tamizaje</> : 'Siguiente'}</button></div>
    <p className="mt-6 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-500">Este instrumento es preventivo. Sus respuestas pueden generar indicadores para valoración, pero no producen diagnósticos clínicos.</p>
  </div>;
}
